# Generated by Django 4.2.5 on 2023-10-25 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0002_category_rename_account_id_member_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 13, 5, 36, 370155, tzinfo=datetime.timezone.utc)),
        ),
    ]
