# Generated by Django 4.2.5 on 2023-10-25 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0003_alter_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_borrowAndReturn.category'),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 13, 7, 54, 538635, tzinfo=datetime.timezone.utc)),
        ),
    ]
