# Generated by Django 4.2.5 on 2023-10-25 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0004_book_category_alter_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 14, 30, 41, 179826, tzinfo=datetime.timezone.utc)),
        ),
    ]
