# Generated by Django 4.2.5 on 2023-10-26 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0005_book_slug_alter_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 25, 15, 11, 38, 832047, tzinfo=datetime.timezone.utc)),
        ),
    ]
