# Generated by Django 4.2.5 on 2023-11-29 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0008_remove_borrowingrecord_member_borrowingrecord_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 28, 13, 11, 7, 410657, tzinfo=datetime.timezone.utc)),
        ),
    ]
