# Generated by Django 4.2.5 on 2023-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0011_alter_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
