# Generated by Django 4.2.5 on 2023-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_borrowAndReturn', '0012_delete_account_alter_borrowingrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isOn',
            field=models.BooleanField(default=True),
        ),
    ]
